all:
    # install pycocotools locally
	python3 setup.py build_ext --inplace
	rm -rf build

install:
	# install pycocotools to the python3 site-packages
	/home/jiaqihan1108/anaconda3/bin/python setup.py build_ext install
	rm -rf build
